---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Hws.
--- DateTime: 2022/7/9 19:03
---
local struct=require "struct"
local l,t = struct.unpack('dLc0', 'aaaabbbb')
print(l)
print(t)